stages:
  - build
  - deploy

build critter:
  stage: build
  image: node:12-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - critter-front
  script:
    - npm install
    - npm run build

deploy critter:
  stage: deploy
  tags:
    - critter-front
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r dist/. ~/front-deployment
    - sudo service java-critter restart  # this requires sudo rights for gitlab user
